#!/bin/bash

if [[ E${SSH_TTY} != E ]]; then
  echo "Not local shell"
  exit 1
fi

if [[ ${1} != "E" ]]; then
  echo "Nutered"
  exit 1
fi

echo "Starting x and running test-display-and-control"
sleep 1

startx /home/pi/RaspPiClojureScreens/ProofOfConcepts/run_test-display-and-control --kiosk

exit 0
